import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Layout/footer'
import Navbar from '@/components/Layout/navbar'
import { TRPCReactProvider } from '@/lib/trpc/react'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/server/auth'

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html lang='en'>
      <body className={`${openSans.variable} antialiased`}>
        <TRPCReactProvider>
          <SessionProvider>
            <Navbar isLoggedIn={!!session} />
            {children}
            <Footer />
          </SessionProvider>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
