// This file is auto-generated by @hey-api/openapi-ts

export const $SizeDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string',
            minLength: 1
        }
    }
} as const;

export const $ReviewDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        productId: {
            type: 'string'
        },
        rating: {
            type: 'integer',
            format: 'int32',
            maximum: 5,
            minimum: 1
        },
        comment: {
            type: 'string',
            maxLength: 500,
            minLength: 0
        }
    },
    required: ['comment', 'productId', 'rating']
} as const;

export const $PromotionProductDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        productVariantId: {
            type: 'string'
        },
        discountedPrice: {
            type: 'number',
            format: 'double'
        },
        startDate: {
            type: 'string',
            format: 'date'
        },
        endDate: {
            type: 'string',
            format: 'date'
        }
    },
    required: ['discountedPrice', 'endDate', 'productVariantId', 'startDate']
} as const;

export const $ProductDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        imageUrl: {
            type: 'string'
        },
        file: {
            type: 'string',
            format: 'binary'
        },
        name: {
            type: 'string',
            minLength: 1
        },
        description: {
            type: 'string',
            minLength: 1
        },
        price: {
            type: 'number'
        },
        stockQuantity: {
            type: 'integer',
            format: 'int32'
        },
        categoryNames: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        sizes: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['price']
} as const;

export const $ProductVariantDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        imageUrl: {
            type: 'string'
        },
        file: {
            type: 'string',
            format: 'binary'
        },
        colorCode: {
            type: 'string',
            minLength: 1
        },
        productId: {
            type: 'string',
            minLength: 1
        },
        price: {
            type: 'number',
            minimum: 0
        },
        stockQuantity: {
            type: 'integer',
            format: 'int32'
        },
        sizes: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['price']
} as const;

export const $OrderDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        orderDate: {
            type: 'string',
            format: 'date-time'
        },
        status: {
            type: 'string'
        },
        orderItems: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/OrderItemDto'
            },
            maxItems: 2147483647,
            minItems: 1
        },
        deliveryFee: {
            type: 'number'
        },
        deliveryAddress: {
            type: 'string'
        },
        totalAmount: {
            type: 'number'
        }
    }
} as const;

export const $OrderItemDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        productVariantId: {
            type: 'string',
            minLength: 1
        },
        quantity: {
            type: 'integer',
            format: 'int32',
            minimum: 1
        },
        size: {
            type: 'string'
        },
        orderId: {
            type: 'string'
        },
        price: {
            type: 'number'
        }
    }
} as const;

export const $Customer = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        phone: {
            type: 'string'
        }
    }
} as const;

export const $PaymentResponseDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        orderId: {
            type: 'string'
        },
        paymentId: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const $CategoryDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string',
            minLength: 1
        }
    }
} as const;

export const $BulkProductVariantDto = {
    type: 'object',
    properties: {
        variants: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ProductVariantDto'
            },
            minItems: 1
        }
    },
    required: ['variants']
} as const;

export const $HeadingDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        title: {
            type: 'string',
            minLength: 1
        },
        imageUrl: {
            type: 'string'
        },
        file: {
            type: 'string',
            format: 'binary'
        }
    }
} as const;