// This file is auto-generated by @hey-api/openapi-ts

export type SizeDto = {
    id?: string;
    name?: string;
};

export type ReviewDto = {
    id?: string;
    productId: string;
    rating: number;
    comment: string;
};

export type PromotionProductDto = {
    id?: string;
    productVariantId: string;
    discountedPrice: number;
    startDate: string;
    endDate: string;
};

export type ProductDto = {
    id?: string;
    imageUrl?: string;
    file?: (Blob | File);
    name?: string;
    description?: string;
    price: number;
    stockQuantity?: number;
    categoryNames?: Array<(string)>;
    sizes?: Array<(string)>;
};

export type ProductVariantDto = {
    id?: string;
    imageUrl?: string;
    file?: (Blob | File);
    colorCode?: string;
    productId?: string;
    price: number;
    stockQuantity?: number;
    sizes?: Array<(string)>;
};

export type OrderDto = {
    id?: string;
    orderDate?: string;
    status?: string;
    orderItems?: Array<OrderItemDto>;
    deliveryFee?: number;
    deliveryAddress?: string;
    totalAmount?: number;
};

export type OrderItemDto = {
    id?: string;
    productVariantId?: string;
    quantity?: number;
    size?: string;
    orderId?: string;
    price?: number;
};

export type Customer = {
    name?: string;
    email?: string;
    phone?: string;
};

export type PaymentResponseDto = {
    id?: string;
    orderId?: string;
    paymentId?: string;
    status?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type CategoryDto = {
    id?: string;
    name?: string;
};

export type BulkProductVariantDto = {
    variants: Array<ProductVariantDto>;
};

export type HeadingDto = {
    id?: string;
    title?: string;
    imageUrl?: string;
    file?: (Blob | File);
};

export type GetApiSizesByIdData = {
    id: string;
};

export type GetApiSizesByIdResponse = SizeDto;

export type PutApiSizesByIdData = {
    id: string;
    requestBody: SizeDto;
};

export type PutApiSizesByIdResponse = SizeDto;

export type DeleteApiSizesByIdData = {
    id: string;
};

export type DeleteApiSizesByIdResponse = void;

export type GetApiSizesResponse = Array<SizeDto>;

export type PostApiSizesData = {
    requestBody: SizeDto;
};

export type PostApiSizesResponse = SizeDto;

export type GetApiReviewsByIdData = {
    id: string;
};

export type GetApiReviewsByIdResponse = ReviewDto;

export type PutApiReviewsByIdData = {
    id: string;
    requestBody: ReviewDto;
};

export type PutApiReviewsByIdResponse = ReviewDto;

export type DeleteApiReviewsByIdData = {
    id: string;
};

export type DeleteApiReviewsByIdResponse = void;

export type GetApiReviewsResponse = Array<ReviewDto>;

export type PostApiReviewsData = {
    requestBody: ReviewDto;
};

export type PostApiReviewsResponse = ReviewDto;

export type GetApiPromotionProductsByIdData = {
    id: string;
};

export type GetApiPromotionProductsByIdResponse = PromotionProductDto;

export type PutApiPromotionProductsByIdData = {
    id: string;
    requestBody: PromotionProductDto;
};

export type PutApiPromotionProductsByIdResponse = PromotionProductDto;

export type DeleteApiPromotionProductsByIdData = {
    id: string;
};

export type DeleteApiPromotionProductsByIdResponse = void;

export type GetApiPromotionProductsResponse = Array<PromotionProductDto>;

export type PostApiPromotionProductsData = {
    requestBody: PromotionProductDto;
};

export type PostApiPromotionProductsResponse = PromotionProductDto;

export type PostApiPromotionProductsBatchData = {
    requestBody: Array<PromotionProductDto>;
};

export type PostApiPromotionProductsBatchResponse = Array<PromotionProductDto>;

export type GetApiProductsByIdData = {
    id: string;
};

export type GetApiProductsByIdResponse = ProductDto;

export type PutApiProductsByIdData = {
    id: string;
    requestBody?: ProductDto;
};

export type PutApiProductsByIdResponse = ProductDto;

export type DeleteApiProductsByIdData = {
    id: string;
};

export type DeleteApiProductsByIdResponse = void;

export type GetApiProductsResponse = Array<ProductDto>;

export type PostApiProductsData = {
    formData?: ProductDto;
};

export type PostApiProductsResponse = ProductDto;

export type GetApiProductVariantsByIdData = {
    id: string;
};

export type GetApiProductVariantsByIdResponse = ProductVariantDto;

export type PutApiProductVariantsByIdData = {
    id: string;
    requestBody?: ProductVariantDto;
};

export type PutApiProductVariantsByIdResponse = ProductVariantDto;

export type DeleteApiProductVariantsByIdData = {
    id: string;
};

export type DeleteApiProductVariantsByIdResponse = void;

export type GetApiProductVariantsData = {
    productId?: string;
};

export type GetApiProductVariantsResponse = Array<ProductVariantDto>;

export type PostApiProductVariantsData = {
    formData?: ProductVariantDto;
};

export type PostApiProductVariantsResponse = ProductVariantDto;

export type PostApiProductVariantsBulkData = {
    formData?: BulkProductVariantDto;
};

export type PostApiProductVariantsBulkResponse = Array<ProductVariantDto>;

export type GetApiOrdersByIdData = {
    id: string;
};

export type GetApiOrdersByIdResponse = OrderDto;

export type PutApiOrdersByIdData = {
    id: string;
    requestBody: OrderDto;
};

export type PutApiOrdersByIdResponse = OrderDto;

export type DeleteApiOrdersByIdData = {
    id: string;
};

export type DeleteApiOrdersByIdResponse = void;

export type PutApiOrdersByIdConfirmData = {
    id: string;
    requestBody: Customer;
};

export type PutApiOrdersByIdConfirmResponse = PaymentResponseDto;

export type GetApiOrdersResponse = Array<OrderDto>;

export type PostApiOrdersData = {
    requestBody: OrderDto;
};

export type PostApiOrdersResponse = OrderDto;

export type GetApiOrdersUserOrdersResponse = Array<OrderDto>;

export type GetApiCategoriesByIdData = {
    id: string;
};

export type GetApiCategoriesByIdResponse = CategoryDto;

export type PutApiCategoriesByIdData = {
    id: string;
    requestBody: CategoryDto;
};

export type PutApiCategoriesByIdResponse = CategoryDto;

export type DeleteApiCategoriesByIdData = {
    id: string;
};

export type DeleteApiCategoriesByIdResponse = void;

export type GetApiCategoriesResponse = Array<CategoryDto>;

export type PostApiCategoriesData = {
    requestBody: CategoryDto;
};

export type PostApiCategoriesResponse = CategoryDto;

export type GetApiHeadingsResponse = Array<HeadingDto>;

export type PostApiHeadingsData = {
    requestBody: HeadingDto;
};

export type PostApiHeadingsResponse = HeadingDto;

export type GetApiHeadingsByIdData = {
    id: string;
};

export type GetApiHeadingsByIdResponse = HeadingDto;

export type DeleteApiHeadingsByIdData = {
    id: string;
};

export type DeleteApiHeadingsByIdResponse = void;

export type $OpenApiTs = {
    '/api/sizes/{id}': {
        get: {
            req: GetApiSizesByIdData;
            res: {
                /**
                 * OK
                 */
                200: SizeDto;
            };
        };
        put: {
            req: PutApiSizesByIdData;
            res: {
                /**
                 * OK
                 */
                200: SizeDto;
            };
        };
        delete: {
            req: DeleteApiSizesByIdData;
            res: {
                /**
                 * No Content
                 */
                204: void;
            };
        };
    };
    '/api/sizes': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<SizeDto>;
            };
        };
        post: {
            req: PostApiSizesData;
            res: {
                /**
                 * Created
                 */
                201: SizeDto;
            };
        };
    };
    '/api/reviews/{id}': {
        get: {
            req: GetApiReviewsByIdData;
            res: {
                /**
                 * OK
                 */
                200: ReviewDto;
            };
        };
        put: {
            req: PutApiReviewsByIdData;
            res: {
                /**
                 * OK
                 */
                200: ReviewDto;
            };
        };
        delete: {
            req: DeleteApiReviewsByIdData;
            res: {
                /**
                 * No Content
                 */
                204: void;
            };
        };
    };
    '/api/reviews': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<ReviewDto>;
            };
        };
        post: {
            req: PostApiReviewsData;
            res: {
                /**
                 * Created
                 */
                201: ReviewDto;
            };
        };
    };
    '/api/promotion-products/{id}': {
        get: {
            req: GetApiPromotionProductsByIdData;
            res: {
                /**
                 * OK
                 */
                200: PromotionProductDto;
            };
        };
        put: {
            req: PutApiPromotionProductsByIdData;
            res: {
                /**
                 * OK
                 */
                200: PromotionProductDto;
            };
        };
        delete: {
            req: DeleteApiPromotionProductsByIdData;
            res: {
                /**
                 * No Content
                 */
                204: void;
            };
        };
    };
    '/api/promotion-products': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<PromotionProductDto>;
            };
        };
        post: {
            req: PostApiPromotionProductsData;
            res: {
                /**
                 * OK
                 */
                200: PromotionProductDto;
            };
        };
    };
    '/api/promotion-products/batch': {
        post: {
            req: PostApiPromotionProductsBatchData;
            res: {
                /**
                 * Created
                 */
                201: Array<PromotionProductDto>;
            };
        };
    };
    '/api/products/{id}': {
        get: {
            req: GetApiProductsByIdData;
            res: {
                /**
                 * OK
                 */
                200: ProductDto;
            };
        };
        put: {
            req: PutApiProductsByIdData;
            res: {
                /**
                 * OK
                 */
                200: ProductDto;
            };
        };
        delete: {
            req: DeleteApiProductsByIdData;
            res: {
                /**
                 * No Content
                 */
                204: void;
            };
        };
    };
    '/api/products': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<ProductDto>;
            };
        };
        post: {
            req: PostApiProductsData;
            res: {
                /**
                 * Created
                 */
                201: ProductDto;
            };
        };
    };
    '/api/product-variants/{id}': {
        get: {
            req: GetApiProductVariantsByIdData;
            res: {
                /**
                 * OK
                 */
                200: ProductVariantDto;
            };
        };
        put: {
            req: PutApiProductVariantsByIdData;
            res: {
                /**
                 * OK
                 */
                200: ProductVariantDto;
            };
        };
        delete: {
            req: DeleteApiProductVariantsByIdData;
            res: {
                /**
                 * No Content
                 */
                204: void;
            };
        };
    };
    '/api/product-variants': {
        get: {
            req: GetApiProductVariantsData;
            res: {
                /**
                 * OK
                 */
                200: Array<ProductVariantDto>;
            };
        };
        post: {
            req: PostApiProductVariantsData;
            res: {
                /**
                 * Created
                 */
                201: ProductVariantDto;
            };
        };
    };
    '/api/product-variants/bulk': {
        post: {
            req: PostApiProductVariantsBulkData;
            res: {
                /**
                 * Created
                 */
                201: Array<ProductVariantDto>;
            };
        };
    };
    '/api/orders/{id}': {
        get: {
            req: GetApiOrdersByIdData;
            res: {
                /**
                 * OK
                 */
                200: OrderDto;
            };
        };
        put: {
            req: PutApiOrdersByIdData;
            res: {
                /**
                 * OK
                 */
                200: OrderDto;
            };
        };
        delete: {
            req: DeleteApiOrdersByIdData;
            res: {
                /**
                 * No Content
                 */
                204: void;
            };
        };
    };
    '/api/orders/{id}/confirm': {
        put: {
            req: PutApiOrdersByIdConfirmData;
            res: {
                /**
                 * Accepted
                 */
                202: PaymentResponseDto;
            };
        };
    };
    '/api/orders': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<OrderDto>;
            };
        };
        post: {
            req: PostApiOrdersData;
            res: {
                /**
                 * Created
                 */
                201: OrderDto;
            };
        };
    };
    '/api/orders/user/orders': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<OrderDto>;
            };
        };
    };
    '/api/categories/{id}': {
        get: {
            req: GetApiCategoriesByIdData;
            res: {
                /**
                 * OK
                 */
                200: CategoryDto;
            };
        };
        put: {
            req: PutApiCategoriesByIdData;
            res: {
                /**
                 * OK
                 */
                200: CategoryDto;
            };
        };
        delete: {
            req: DeleteApiCategoriesByIdData;
            res: {
                /**
                 * No Content
                 */
                204: void;
            };
        };
    };
    '/api/categories': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<CategoryDto>;
            };
        };
        post: {
            req: PostApiCategoriesData;
            res: {
                /**
                 * Created
                 */
                201: CategoryDto;
            };
        };
    };
    '/api/headings': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<HeadingDto>;
            };
        };
        post: {
            req: PostApiHeadingsData;
            res: {
                /**
                 * Created
                 */
                201: HeadingDto;
            };
        };
    };
    '/api/headings/{id}': {
        get: {
            req: GetApiHeadingsByIdData;
            res: {
                /**
                 * OK
                 */
                200: HeadingDto;
            };
        };
        delete: {
            req: DeleteApiHeadingsByIdData;
            res: {
                /**
                 * No Content
                 */
                204: void;
            };
        };
    };
};